title: My personal porfolio - Sebastian Schott
email: SeabassSchott@gmail.com
description: "Hi, I'm Sebastian! I'm a VDC Manager passionate about transforming construction through technology, automation, and smart coordination processes."
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://sebshott.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Sebastian Schott # add your name
author-pic: seb_headshot.jpg
about-author: My name is Sebastian Schott. I’m a VDC Manager with 8 years of construction industry experience specializing in automation, coordination methodologies, and emerging technologies. Passionate about transforming construction workflows through innovative scripting solutions and smart project delivery.

# Contact links
email: SeabassSchott@gmail.com
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: https://www.linkedin.com/in/sebastian-schott-vdc/
github:  # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
